[package]
name = "scc"
description = "scalable concurrent data structures for database management systems"
version = "0.2.3"
authors = ["Changgyoo Park <wvwwvwwv@me.com>", "Changgyoo Park <changgyoo.park@sap.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/wvwwvwwv/scc/"
license = "MIT"
categories = ["concurrency", "data-structures"]
keywords = ["hashmap", "hashtable"]

[dependencies]
crossbeam-epoch="^0.9"
libc="^0.2.80"

[dev-dependencies]
proptest="^0.10.1"
