name: SCC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Debug - Build
        run: cargo build --verbose
      - name: Debug - Run tests
        run: cargo test -- --nocapture
      - name: Release - Run tests
        run: cargo test --release -- --nocapture
